# See: https://github.com/pmarsceill/just-the-docs/blob/master/_config.yml
title: LTSP
description: Linux Terminal Server Project
remote_theme: pmarsceill/just-the-docs

url: "https://ltsp.org" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
logo: "/logo.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "LTSP on GitHub":
    - "//github.com/ltsp/ltsp"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2000-2021 the <a href=\"https://github.com/ltsp/ltsp/graphs/contributors\">LTSP developers</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10

# plugins:
#   - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false


kramdown:
  smart_quotes: apos,apos,quot,quot
